apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: stonesoup-spring-boot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stonesoup-spring-boot
    app.kubernetes.io/part-of: test-application
  name: stonesoup-spring-boot
  namespace: cmoullia-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: stonesoup-spring-boot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: stonesoup-spring-boot
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:stonesoup-spring-boot
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
