apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: stonesoup-spring-boot-k4kf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stonesoup-spring-boot-k4kf
    app.kubernetes.io/part-of: test-application
  name: stonesoup-spring-boot-k4kf
  namespace: cmoullia-tenant
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: stonesoup-spring-boot-k4kf
    weight: 100
status: {}
