apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: stonesoup-spring-boot-k4kf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: stonesoup-spring-boot-k4kf
    app.kubernetes.io/part-of: test-application
  name: stonesoup-spring-boot-k4kf
  namespace: cmoullia-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: stonesoup-spring-boot-k4kf
status:
  loadBalancer: {}
